Java nd
ShehrozIrfan/learn-programming-fundamentals pull request #3
Opened 2023-01-02 15:27 UTC by enn-dee

Hello 
I have added some basic content to the project . The content covers the following topics:
- Introduction About JAVA
- Basic Syntax 
- Basic Syntax /1. Comments . /2 Variables . /3 Data Types.
-Please let me know if you have any feedback or suggestions for improvement.

2023-01-03 04:55 UTC, ShehrozIrfan requested changes
Overall looks good. Good work.

Just need some changes:
- Remove the extra line breaks
- Add the proper formatting so that it looks good

2023-01-03 04:55 UTC, ShehrozIrfan commented on JAVA/1.Intro/intro.md
> +Java is a programming language and computing platform first released by
Good work.

2023-01-03 04:55 UTC, ShehrozIrfan commented on JAVA/2.Basic Syntax/Basic Syntax.md
> +
Remove the extra lines from the whole file. There must be only one line space if needed.

2023-01-03 04:55 UTC, ShehrozIrfan commented on JAVA/2.Basic Syntax/Basic Syntax.md
> +
Remove this extra line.

2023-01-03 04:55 UTC, ShehrozIrfan commented on JAVA/2.Basic Syntax/Basic Syntax.md
> +
Remove line

2023-01-03 04:55 UTC, ShehrozIrfan commented on JAVA/2.Basic Syntax/Basic Syntax.md
> +# Variables
Add a line break above this line, and heading should be: `## 3. Variables`

2023-01-03 11:10 UTC, enn-dee commented
Review Changes

2023-01-04 04:57 UTC, ShehrozIrfan approved these changes
Looks good to merge 🎉
Thank you for your contribution 🚀

2023-01-04 04:58 UTC, merged