more pointers
ShehrozIrfan/learn-programming-fundamentals pull request #8
Opened 2023-10-11 10:35 UTC by KaiTardor

2023-10-11 17:32 UTC, ShehrozIrfan requested changes
Good work, interesting to see the pointers in action.

Just need a minor change to remove the `.vscode/settings.json` file, because it's not needed.

2023-10-11 17:32 UTC, ShehrozIrfan commented on .vscode/settings.json
> +{
Change: Remove this file, we don't need this.

2023-10-11 18:14 UTC, KaiTardor commented on .vscode/settings.json
> +{
Okey

2023-10-12 04:41 UTC, ShehrozIrfan approved these changes
LGTM

2023-10-12 04:41 UTC, merged

2023-10-12 04:42 UTC, ShehrozIrfan commented
@KaiTardor 

Perfect 🚀

You can follow me and star this repo for further updates.
Have fun!